version: 2
jobs:
  build-job:
    working_directory: ~/sdcs-slack-bot
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Jest Client and Mocha Server Suites
          command: "npm run test"
      - run:
          name: Cypress End 2 End
          command: "npm run build && npm run cy:test"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
